"""empty message

Revision ID: b034b7849207
Revises: 
Create Date: 2020-05-08 16:47:38.468317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b034b7849207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('servings', sa.String(length=120), nullable=True),
    sa.Column('ingridients', sa.String(length=4500), nullable=True),
    sa.Column('cooktime', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=4500), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('cooktips', sa.String(length=4500), nullable=True),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cooking')
    # ### end Alembic commands ###
